In [ ]:
# Top 10 movie in sales: ROI (sales - budget) + factors: Director, Actor, license , runtime - Eliza

In [1]:
# import dependencies 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# read in cleaned data

clean_data_df = pd.read_csv('clean_files_output_ey.csv')
clean_data_df.dtypes

clean_data_df.tail()

/var/folders/62/f2x4shss4kq25jc_zwqwlh740000gn/T/ipykernel_25967/1184130735.py:3: DtypeWarning: Columns (4,5,11,13,18,19,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_data_df = pd.read_csv('correct_clean_combo_movie_data.csv')

,Unnamed: 0.1,year,Unnamed: 0,title,Movie Info,Distributor,budget,Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),...,release_date,runtime_minutes,rating,director,star,name,released,writer,gross.1,company
365127,365127,0.0,0.0,Madeleine,0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0,0,0,0,0,0.0,0
365128,365128,0.0,0.0,Human Nature,0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,Cullen McFater,Cullen McFater,0,0,0,0.0,0
365129,365129,0.0,0.0,Bartali,0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,Jonathan Newman,0,0,0,0,0.0,0
365130,365130,0.0,0.0,Intrepid,0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0,0,0,0,0,0.0,0
365131,365131,0.0,0.0,The Mechanic,0,0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0,0,0,0,0,0.0,0

In [ ]:
# place holder dataframe - cleaned_movies_df

In [ ]:
# Calculate ROI
movies_df['ROI'] = movies_df['gross'] - movies_df['budget']

In [ ]:
# Sort by ROI and select top 10
top_movies = movies_df.sorted_values('ROI', ascending=False).head(10)

In [ ]:
# Bar Plot: Top 10 Movies by ROI (To compare of the financial performance of the movies)
plt.figure(figsize=(12, 6)) 
plt.bar(top_movies['title'], top_movies['ROI'], color='skyblue')
plt.title('Top 10 Movies by ROI')
plt.xlabel('Movie Title')
plt.ylabel('ROI')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
# Heatmap: Factors for Top 10 Movies by ROI
factor = ['director', 'actor', 'license', 'runtime']